# Generated by Django 3.2.7 on 2023-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_cast_show_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='cast_show_link',
        ),
        migrations.AddField(
            model_name='show',
            name='cast_show_link',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
