# Generated by Django 3.2.7 on 2022-11-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_newshow_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newshow',
            name='date',
            field=models.CharField(max_length=254),
        ),
    ]
