# Generated by Django 3.2.7 on 2022-11-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_newshow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newshow',
            name='address_ticket',
            field=models.TextField(max_length=254),
        ),
    ]
