# Generated by Django 3.2.7 on 2022-11-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_newshow_address_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewShow',
            new_name='New',
        ),
        migrations.RenameModel(
            old_name='UpcomingShow',
            new_name='Upcoming',
        ),
    ]
