# Generated by Django 3.2.7 on 2022-11-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20221126_0948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewShow',
            new_name='Show',
        ),
        migrations.RenameModel(
            old_name='UpcomingShow',
            new_name='Upcoming',
        ),
    ]
