# Generated by Django 3.2.7 on 2022-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221126_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='image_show',
            new_name='show_poster',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='image_sponsor',
            new_name='sponsor_image',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='image_ticket',
            new_name='ticket_retail_image',
        ),
        migrations.RemoveField(
            model_name='show',
            name='address_ticket',
        ),
        migrations.RemoveField(
            model_name='show',
            name='content_show',
        ),
        migrations.RemoveField(
            model_name='show',
            name='web_ticket',
        ),
        migrations.AddField(
            model_name='show',
            name='show_content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='sponsor_name',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_retail_address',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_retail_name',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_retail_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
