# Generated by Django 3.2.7 on 2022-11-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221126_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='ticket_retail_address',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='ticket_retail_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
