# Generated by Django 3.2.7 on 2023-01-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230114_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcoming',
            old_name='date',
            new_name='date_location',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='location',
        ),
    ]
