# Generated by Django 3.2.7 on 2023-01-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230114_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='date_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
