# Generated by Django 3.2.7 on 2023-01-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_upcoming_date_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming',
            name='date_location',
        ),
        migrations.AddField(
            model_name='upcoming',
            name='date',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='date_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='date_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='location_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='location_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
