# Generated by Django 3.2.7 on 2023-03-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230114_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_sound_bite',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
