# Generated by Django 3.2.7 on 2023-05-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_show_show_sound_bite'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ticket_retail_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_retail_name_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_retail_url_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
