# Generated by Django 3.2.7 on 2023-07-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20230503_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='sponsor_image',
        ),
        migrations.RemoveField(
            model_name='show',
            name='sponsor_name',
        ),
        migrations.RemoveField(
            model_name='show',
            name='sponsor_url',
        ),
    ]
