# Generated by Django 5.1.5 on 2026-02-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20230715_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='ticket_retail_image_2',
        ),
        migrations.RemoveField(
            model_name='show',
            name='ticket_retail_name_2',
        ),
        migrations.RemoveField(
            model_name='show',
            name='ticket_retail_url_2',
        ),
    ]
