# Generated by Django 5.1.5 on 2026-02-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_show_ticket_retail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_poster',
            field=models.ImageField(blank=True, default='', upload_to=''),
            preserve_default=False,
        ),
    ]
