# Generated by Django 5.1.5 on 2026-02-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_show_show_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeechingHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('mh_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('mh_poster', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.DeleteModel(
            name='Upcoming',
        ),
    ]
