# Generated by Django 5.1.5 on 2026-02-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_meechinghall_delete_show_delete_upcoming'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeechingHall',
            new_name='MeechingHome',
        ),
    ]
