# Generated by Django 5.1.5 on 2026-02-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_show_upcoming_delete_meechinghome'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeechingHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('meeching_text', models.TextField(blank=True, max_length=400, null=True)),
                ('meeching_poster', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.DeleteModel(
            name='Upcoming',
        ),
    ]
