# Generated by Django 5.1.5 on 2026-02-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_meechinghome_delete_show_delete_upcoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.CharField(blank=True, max_length=254, null=True)),
                ('ticket_retail_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ticket_retail_name', models.CharField(blank=True, max_length=254, null=True)),
                ('ticket_retail_url', models.CharField(blank=True, max_length=254, null=True)),
                ('ticket_retail_address', models.TextField(blank=True, max_length=400, null=True)),
                ('show_poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('show_sound_bite', models.TextField(blank=True, max_length=1000, null=True)),
                ('show_content', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.CharField(blank=True, max_length=254, null=True)),
                ('location_2', models.CharField(blank=True, max_length=254, null=True)),
                ('date_2', models.CharField(blank=True, max_length=254, null=True)),
                ('location_3', models.CharField(blank=True, max_length=254, null=True)),
                ('date_3', models.CharField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MeechingHome',
        ),
    ]
