# Generated by Django 5.1.5 on 2026-02-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_meeching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeching',
            name='meeching_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
