# Generated by Django 3.2.7 on 2022-11-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='price',
            new_name='adult_price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='child_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
