# Generated by Django 3.2.7 on 2022-11-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='web',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
