# Generated by Django 3.2.7 on 2023-01-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_show_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
