# Generated by Django 3.2.7 on 2023-01-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_show_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
