# Generated by Django 3.2.7 on 2023-07-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20230428_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_date',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='place',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='web',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
