# Generated by Django 5.1.5 on 2026-02-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeechingHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('ideas_url', models.CharField(blank=True, max_length=254, null=True)),
                ('ideas_image', models.ImageField(blank=True, upload_to='')),
                ('memories_url', models.CharField(blank=True, max_length=254, null=True)),
                ('memories_image', models.ImageField(blank=True, upload_to='')),
                ('petition_url', models.CharField(blank=True, max_length=254, null=True)),
                ('petition_image', models.ImageField(blank=True, upload_to='')),
                ('meeching_hall_content', models.TextField(blank=True, max_length=2000, null=True)),
                ('meeching_hall_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
