# Generated by Django 5.1.5 on 2026-02-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeching_hall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meechinghall',
            name='ideas',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='meechinghall',
            name='meeching_hall_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='meechinghall',
            name='meeching_hall_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='meechinghall',
            name='petition',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
