# Generated by Django 5.1.5 on 2026-02-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeching_hall', '0002_meechinghall_ideas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meechinghall',
            old_name='ideas',
            new_name='name',
        ),
    ]
