# Generated by Django 5.1.5 on 2026-02-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeching_hall', '0003_rename_ideas_meechinghall_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meechinghall',
            old_name='petition',
            new_name='meeching_hall_petition',
        ),
    ]
