# Generated by Django 5.1.5 on 2026-02-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeching_hall', '0004_rename_petition_meechinghall_meeching_hall_petition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meechinghall',
            name='name',
            field=models.CharField(default='Default Name', max_length=254),
            preserve_default=False,
        ),
    ]
