# Generated by Django 3.2.7 on 2022-11-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_actor_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='film',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
