# Generated by Django 3.2.7 on 2022-11-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0003_actor_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='position',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='position',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
