# Generated by Django 3.2.7 on 2023-01-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0004_auto_20221126_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='cast_show_link',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
