# Generated by Django 3.2.7 on 2023-01-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0005_show_cast_show_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='cast_show_link',
            new_name='gallery_show_link',
        ),
    ]
