# Generated by Django 3.2.7 on 2023-02-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0006_rename_cast_show_link_show_gallery_show_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='testimonial_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='testimonial_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='testimonial_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
