# Generated by Django 3.2.7 on 2023-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0008_show_testimonial_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
